### ISSUE TITLE
in my case I had to copy layout.blade.php manually

### ISSUE THREAD

**Issue by vesper8** [osamaAbdullah/nova-collapsible-sidebar#3]
For some reason nova:publish or vendor:publish -> nova-views was not publishing the layout.blade.php view

No idea why.. even when I used --force

I had to copy it manually from https://github.com/laravel/nova/blob/3.0/resources/views/layout.blade.php

**Comment by osamaAbdullah** [comment]
this issue is not related to the package probably something is working with your environment setup.
